[MSDK-72] Fix swagger spec generation
Keypr/helium pull request #36
Opened 2019-10-30 17:07 UTC by SsIDit

Add "sequence" processing

2019-10-30 17:08 UTC, ukhanoff approved these changes

2019-10-30 17:27 UTC, lampapos commented
@SsIDit PTAL at Travis

2019-10-31 08:06 UTC, Vandalko requested changes
plz add the corresponding test

2019-10-31 09:27 UTC, Vandalko approved these changes

2019-10-31 09:41 UTC, ukhanoff approved these changes

2019-10-31 12:39 UTC, lampapos approved these changes

2019-10-31 12:39 UTC, merged